# Generated by Django 5.1.6 on 2025-04-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='supabase_path',
            field=models.CharField(blank=True, help_text="Supabase bucket key: e.g. 'CourseFolder/lecture1.mp4'", max_length=1024, null=True),
        ),
    ]
