# Generated by Django 5.1.6 on 2025-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_supabase_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='supabase_path',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='file_path',
            field=models.CharField(blank=True, help_text="Supabase storage path, e.g. 'course_folder/lesson.mp4'", max_length=500),
        ),
    ]
